README.md

1-test-issue: Add ReciVeci Web page link

---

config.xml
package-lock.json
package.json
src/app/app.module.ts
src/pages/dashboard/dashboard.html
src/pages/dashboard/dashboard.scss
src/pages/dashboard/dashboard.ts
src/theme/variables.scss

Creación de contactos (mail, facebook, twitter) con enlaces a las redes sociales y acceso al cliente de correo del celular

#22 Creacion contactos para menu principal

---

config.xml
package-lock.json

Closes #53 
Se actualizó los valores de correo y sitio Web de ReciVeci

#53 versión 2.1.2 y atributos de email y sitio Web de ReciVeci

---

src/app/app.component.ts
src/pages/tour/tour.ts

- Se realizo la corrección de bug.
- Se añadio codigo comentado del native storage para realizar pruebas en móviles eliminando el localstorage de javascript.

52 tour primera bug

---

src/pages/social-networks/social-networks.ts
src/pages/tour/tour.ts

- Métodos modificados para acceder a redes sociales en app.

#48 tour bug arreglado y modificado codigo en tourpage y socialNetworkPage

---

config.xml
src/pages/dashboard/dashboard.ts
src/pages/tabs/tabs.ts

#71 Solved errors to issue #71 and #39

---

src/pages/entrega/entrega.html
src/pages/entrega/entrega.ts

- Se realizo la correcion de bugs en el mapa

#83 #65 #56 bugs mapa correccion

---

src/pages/social-networks/social-networks.html
src/pages/social-networks/social-networks.ts

Se borró CC del mail y se enlazó cada item correspondiente a una red social

#75 Quitar CC y enlace de item de redes sociales

---

src/pages/recycler-form/recycler-form.html
src/pages/recycler-form/recycler-form.ts

#111 Correccion formulario reciclador

---

package-lock.json
src/pages/reciclador/reciclador.html
src/pages/recycler-form/recycler-form.html
src/pages/tabs/tabs.html

Se añadió el campo sueño del reciclador en el formulario almacenando el campo en la base de datos y se muestra el sueño en el perfil del reciclador, además se oculto opciones en el menú (perfil, acerca de)

#116 #118 campo sueño del reciclador y ocultar opciones

---

config.xml
package-lock.json
package.json
src/pages/map/map.html
src/pages/map/map.scss
src/pages/map/map.ts

Se dio funcionalidad al botón de llamada y aparece la letra inicial del nombre en caso que no tenga foto el reciclador

#137 mapa funcionalidad

---

package-lock.json
src/pages/reciclador/reciclador.html
src/pages/recycler-form/recycler-form.html
src/pages/recycler-form/recycler-form.ts

El campo de material que recibe ya se valida y un texto que indique que son número de recolecciones

#166 Correcciones perfil reciclador

---

src/pages/exchange/exchange.html
src/pages/exchange/exchange.scss
src/pages/modal/modal.html
src/pages/modal/modal.scss

Mejoras de diseño en la pagina de la lista de canjes y modal.

#191 Exchange Design enhancement

---

src/pages/modal/modal.html
src/pages/modal/modal.ts

Un solo mensaje de confirmación cuando se realiza el canje.

#200 Exchange Modal message only one toast

---

config.xml

#207 Bloquear la rotación horizontal

---

src/pages/couponModal/couponModal.ts
src/pages/modal/modal.ts

#226 Exchange design change toast to modal

---

src/pages/delivery/delivery.html
src/pages/delivery/delivery.scss
src/pages/delivery/delivery.ts

Cambio de colores en las validaciones/errores.
Desactivado el botón cuando se realiza el tap/clic.
Se quito la imagen de la cámara cuando se toma la foto.
Se agrando la imagen a toda la sección (se distorsiona debido al sentido de orientación del télefono), se puso la dirección de la cámara (Predeterminado la cámara principal (puede no funcionar en todos los dispositivos), Predeterminado en horizontal (puede no funcionar en todos los dispositivos especial IOs debido a que se utiliza otros parámetros correctOrientation y no popoverOptions)).
Se dio un z-index a la opción de regresar para no ocultarse con la foto.

#231 Delivery design

---

src/app/app.component.ts
src/pages/dashboard/dashboard.ts
src/pages/login/login.ts
src/pages/register/register.html
src/pages/register/register.scss
src/pages/register/register.ts

Revisar si se corrige el problema en IOs (en sistema Android no da problema).

#241 Register page

---

src/pages/couponModal/couponModal.html
src/pages/couponModal/couponModal.ts
src/pages/exchange/exchange.scss
src/pages/exchange/exchange.ts
src/pages/modal/modal.ts

Se soluciono el problema de la fecha en el cupón cuando se canjea el cupón.

#240 Exchange page solved bugs

---

src/app/app.html
src/app/app.scss

#251 Estilo menú lateral

---

src/pages/delivery/delivery.html
src/pages/delivery/delivery.scss
src/pages/delivery/delivery.ts

Se agregó:
Imagen de la cámara, después de tomar la foto.
Imagen Range en IOs se hicieron más pequeñas.
Cambio de texto en mensajes de error/validación del formulario de entrega.
Icono Spinner Guardando.

#250 Delivery design, solved error
